server:
  port: 8083
spring:
  application:
    name: search-service
  rabbitmq:
    host: 192.168.1.100
    virtual-host: /leyou
    password: leyou
    username: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.100:9300
  jackson:
    default-property-inclusion: non_null   #去除空的字段
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期